apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: thefoosthebars.myk8s.io
spec:
  group: myk8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
  scope: Namespaced
  names:
    plural: thefoosthebars
    singular: thefoosthebars
    kind: TheFooTheBar
    shortNames:
      - tfb
